# Generated by Django 5.1.2 on 2024-11-05 22:59

import django.db.models.deletion
import profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=15)),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures', validators=[profiles.validators.validate_image_size])),
                ('role', models.CharField(choices=[('Citizen Journalist', 'Citizen Journalist'), ('Confirmed Journalist', 'Confirmed Journalist'), ('Moderator', 'Moderator'), ('Admin', 'Admin')], default='Citizen Journalist', max_length=30)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('confirmed_journalist', 'Automatically approve all posts by this user'), ('moderator', 'This user has moderation permissions')],
            },
        ),
    ]
