# Generated by Django 5.1.2 on 2024-11-07 22:41

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[profiles.validators.validate_date_of_birth]),
        ),
    ]
