# Generated by Django 5.1.2 on 2024-11-05 22:14

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', validators=[profiles.validators.validate_image_size]),
        ),
    ]
